### ISSUE TITLE
Normalization of negative speed values doesn't work

### ISSUE THREAD

**Issue by reuank** [PTScientists/MANIros#17]
When xDistance is < 0 in the RoverControl message (backwards driving), the speed output should be < 0 and in [-1....0). However, the published values are < -1.

See: https://github.com/PTScientists/MANIros/blob/vector-protocol/scripts/driving/adapter/control_adapter.py

**Comment by scalingsolution** [comment]
This should be fixed now on the current teleportation branch. 
I adjusted the vector protocol to run independently from ROS and implemented some basic tests.
